// Generated by llvm2cpp - DO NOT MODIFY!

#include <llvm/Pass.h>
#include <llvm/PassManager.h>
#include <llvm/ADT/SmallVector.h>
#include <llvm/Analysis/Verifier.h>
#include <llvm/Assembly/PrintModulePass.h>
#include <llvm/IR/BasicBlock.h>
#include <llvm/IR/CallingConv.h>
#include <llvm/IR/Constants.h>
#include <llvm/IR/DerivedTypes.h>
#include <llvm/IR/Function.h>
#include <llvm/IR/GlobalVariable.h>
#include <llvm/IR/InlineAsm.h>
#include <llvm/IR/Instructions.h>
#include <llvm/IR/LLVMContext.h>
#include <llvm/IR/Module.h>
#include <llvm/Support/FormattedStream.h>
#include <llvm/Support/MathExtras.h>
#include <algorithm>
using namespace llvm;

Module* makeLLVMModule();

int main(int argc, char**argv) {
  Module* Mod = makeLLVMModule();
  verifyModule(*Mod, PrintMessageAction);
  PassManager PM;
  PM.add(createPrintModulePass(&outs()));
  PM.run(*Mod);
  return 0;
}


Module* makeLLVMModule() {
 // Module Construction
 Module* mod = new Module("load_cpp_bc.bc", getGlobalContext());
 mod->setDataLayout("e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64-S128");
 mod->setTargetTriple("x86_64-unknown-linux-gnu");
 
 // Type Definitions
 std::vector<Type*>FuncTy_0_args;
 FuncTy_0_args.push_back(IntegerType::get(mod->getContext(), 32));
 FuncTy_0_args.push_back(IntegerType::get(mod->getContext(), 32));
 FunctionType* FuncTy_0 = FunctionType::get(
  /*Result=*/IntegerType::get(mod->getContext(), 32),
  /*Params=*/FuncTy_0_args,
  /*isVarArg=*/false);
 
 PointerType* PointerTy_1 = PointerType::get(IntegerType::get(mod->getContext(), 32), 0);
 
 
 // Function Declarations
 
 Function* func__Z3addii = mod->getFunction("_Z3addii");
 if (!func__Z3addii) {
 func__Z3addii = Function::Create(
  /*Type=*/FuncTy_0,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"_Z3addii", mod); 
 func__Z3addii->setCallingConv(CallingConv::C);
 }
 AttributeSet func__Z3addii_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::NoUnwind);
    B.addAttribute(Attribute::UWTable);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func__Z3addii_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func__Z3addii->setAttributes(func__Z3addii_PAL);
 
 Function* func__Z3subii = mod->getFunction("_Z3subii");
 if (!func__Z3subii) {
 func__Z3subii = Function::Create(
  /*Type=*/FuncTy_0,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"_Z3subii", mod); 
 func__Z3subii->setCallingConv(CallingConv::C);
 }
 AttributeSet func__Z3subii_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::NoUnwind);
    B.addAttribute(Attribute::UWTable);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func__Z3subii_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func__Z3subii->setAttributes(func__Z3subii_PAL);
 
 // Global Variable Declarations

 
 // Constant Definitions
 ConstantInt* const_int32_2 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("1"), 10));
 
 // Global Variable Definitions
 
 // Function Definitions
 
 // Function: _Z3addii (func__Z3addii)
 {
  Function::arg_iterator args = func__Z3addii->arg_begin();
  Value* int32_a = args++;
  int32_a->setName("a");
  Value* int32_b = args++;
  int32_b->setName("b");
  
  BasicBlock* label_entry = BasicBlock::Create(mod->getContext(), "entry",func__Z3addii,0);
  
  // Block entry (label_entry)
  AllocaInst* ptr_a_addr = new AllocaInst(IntegerType::get(mod->getContext(), 32), "a.addr", label_entry);
  ptr_a_addr->setAlignment(4);
  AllocaInst* ptr_b_addr = new AllocaInst(IntegerType::get(mod->getContext(), 32), "b.addr", label_entry);
  ptr_b_addr->setAlignment(4);
  StoreInst* void_3 = new StoreInst(int32_a, ptr_a_addr, false, label_entry);
  void_3->setAlignment(4);
  StoreInst* void_4 = new StoreInst(int32_b, ptr_b_addr, false, label_entry);
  void_4->setAlignment(4);
  LoadInst* int32_5 = new LoadInst(ptr_a_addr, "", false, label_entry);
  int32_5->setAlignment(4);
  LoadInst* int32_6 = new LoadInst(ptr_b_addr, "", false, label_entry);
  int32_6->setAlignment(4);
  BinaryOperator* int32_add = BinaryOperator::Create(Instruction::Add, int32_5, int32_6, "add", label_entry);
  ReturnInst::Create(mod->getContext(), int32_add, label_entry);
  
 }
 
 // Function: _Z3subii (func__Z3subii)
 {
  Function::arg_iterator args = func__Z3subii->arg_begin();
  Value* int32_a_8 = args++;
  int32_a_8->setName("a");
  Value* int32_b_9 = args++;
  int32_b_9->setName("b");
  
  BasicBlock* label_entry_10 = BasicBlock::Create(mod->getContext(), "entry",func__Z3subii,0);
  
  // Block entry (label_entry_10)
  AllocaInst* ptr_a_addr_11 = new AllocaInst(IntegerType::get(mod->getContext(), 32), "a.addr", label_entry_10);
  ptr_a_addr_11->setAlignment(4);
  AllocaInst* ptr_b_addr_12 = new AllocaInst(IntegerType::get(mod->getContext(), 32), "b.addr", label_entry_10);
  ptr_b_addr_12->setAlignment(4);
  StoreInst* void_13 = new StoreInst(int32_a_8, ptr_a_addr_11, false, label_entry_10);
  void_13->setAlignment(4);
  StoreInst* void_14 = new StoreInst(int32_b_9, ptr_b_addr_12, false, label_entry_10);
  void_14->setAlignment(4);
  LoadInst* int32_15 = new LoadInst(ptr_a_addr_11, "", false, label_entry_10);
  int32_15->setAlignment(4);
  LoadInst* int32_16 = new LoadInst(ptr_b_addr_12, "", false, label_entry_10);
  int32_16->setAlignment(4);
  BinaryOperator* int32_sub = BinaryOperator::Create(Instruction::Sub, int32_15, int32_16, "sub", label_entry_10);
  ReturnInst::Create(mod->getContext(), int32_sub, label_entry_10);
  
 }
 
 return mod;
}
