/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJni */

#ifndef _Included_HelloJni
#define _Included_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJni
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_HelloJni_get
  (JNIEnv *, jobject);

/*
 * Class:     HelloJni
 * Method:    set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_HelloJni_set
  (JNIEnv *, jobject, jint);

/*
 * Class:     HelloJni
 * Method:    setUser
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HelloJni_setUser
  (JNIEnv *, jobject, jstring);

/*
 * Class:     HelloJni
 * Method:    getUser
 * Signature: (LUserBase;)V
 */
JNIEXPORT void JNICALL Java_HelloJni_getUser
  (JNIEnv *, jobject, jobject);

/*
 * Class:     HelloJni
 * Method:    setUserList
 * Signature: (Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_HelloJni_setUserList
  (JNIEnv *, jobject, jobject);

/*
 * Class:     HelloJni
 * Method:    getUserList
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_HelloJni_getUserList
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
