// Generated by llvm2cpp - DO NOT MODIFY!

#include <llvm/Pass.h>
#include <llvm/PassManager.h>
#include <llvm/ADT/SmallVector.h>
#include <llvm/Analysis/Verifier.h>
#include <llvm/Assembly/PrintModulePass.h>
#include <llvm/IR/BasicBlock.h>
#include <llvm/IR/CallingConv.h>
#include <llvm/IR/Constants.h>
#include <llvm/IR/DerivedTypes.h>
#include <llvm/IR/Function.h>
#include <llvm/IR/GlobalVariable.h>
#include <llvm/IR/InlineAsm.h>
#include <llvm/IR/Instructions.h>
#include <llvm/IR/LLVMContext.h>
#include <llvm/IR/Module.h>
#include <llvm/Support/FormattedStream.h>
#include <llvm/Support/MathExtras.h>
#include <algorithm>
using namespace llvm;

Module* makeLLVMModule();

int main(int argc, char**argv) {
  Module* Mod = makeLLVMModule();
  verifyModule(*Mod, PrintMessageAction);
  PassManager PM;
  PM.add(createPrintModulePass(&outs()));
  PM.run(*Mod);
  return 0;
}


Module* makeLLVMModule() {
 // Module Construction
 Module* mod = new Module("load_cpp_bc.bc", getGlobalContext());
 mod->setDataLayout("e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64-S128");
 mod->setTargetTriple("x86_64-unknown-linux-gnu");
 
 // Type Definitions
 std::vector<Type*>FuncTy_0_args;
 FuncTy_0_args.push_back(IntegerType::get(mod->getContext(), 32));
 FuncTy_0_args.push_back(IntegerType::get(mod->getContext(), 32));
 FunctionType* FuncTy_0 = FunctionType::get(
  /*Result=*/IntegerType::get(mod->getContext(), 32),
  /*Params=*/FuncTy_0_args,
  /*isVarArg=*/false);
 
 PointerType* PointerTy_1 = PointerType::get(IntegerType::get(mod->getContext(), 32), 0);
 
 PointerType* PointerTy_2 = PointerType::get(FuncTy_0, 0);
 
 
 // Function Declarations
 
 Function* func_add = mod->getFunction("add");
 if (!func_add) {
 func_add = Function::Create(
  /*Type=*/FuncTy_0,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"add", mod); 
 func_add->setCallingConv(CallingConv::C);
 }
 AttributeSet func_add_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::UWTable);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func_add_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func_add->setAttributes(func_add_PAL);
 
 Function* func__Z8deep_addii = mod->getFunction("_Z8deep_addii");
 if (!func__Z8deep_addii) {
 func__Z8deep_addii = Function::Create(
  /*Type=*/FuncTy_0,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"_Z8deep_addii", mod); // (external, no body)
 func__Z8deep_addii->setCallingConv(CallingConv::C);
 }
 AttributeSet func__Z8deep_addii_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func__Z8deep_addii_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func__Z8deep_addii->setAttributes(func__Z8deep_addii_PAL);
 
 Function* func_sub = mod->getFunction("sub");
 if (!func_sub) {
 func_sub = Function::Create(
  /*Type=*/FuncTy_0,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"sub", mod); 
 func_sub->setCallingConv(CallingConv::C);
 }
 AttributeSet func_sub_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::UWTable);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func_sub_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func_sub->setAttributes(func_sub_PAL);
 
 Function* func__Z8deep_subii = mod->getFunction("_Z8deep_subii");
 if (!func__Z8deep_subii) {
 func__Z8deep_subii = Function::Create(
  /*Type=*/FuncTy_0,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"_Z8deep_subii", mod); // (external, no body)
 func__Z8deep_subii->setCallingConv(CallingConv::C);
 }
 AttributeSet func__Z8deep_subii_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func__Z8deep_subii_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func__Z8deep_subii->setAttributes(func__Z8deep_subii_PAL);
 
 // Global Variable Declarations

 
 // Constant Definitions
 ConstantInt* const_int32_3 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("1"), 10));
 
 // Global Variable Definitions
 
 // Function Definitions
 
 // Function: add (func_add)
 {
  Function::arg_iterator args = func_add->arg_begin();
  Value* int32_a = args++;
  int32_a->setName("a");
  Value* int32_b = args++;
  int32_b->setName("b");
  
  BasicBlock* label_entry = BasicBlock::Create(mod->getContext(), "entry",func_add,0);
  
  // Block entry (label_entry)
  AllocaInst* ptr_a_addr = new AllocaInst(IntegerType::get(mod->getContext(), 32), "a.addr", label_entry);
  ptr_a_addr->setAlignment(4);
  AllocaInst* ptr_b_addr = new AllocaInst(IntegerType::get(mod->getContext(), 32), "b.addr", label_entry);
  ptr_b_addr->setAlignment(4);
  StoreInst* void_4 = new StoreInst(int32_a, ptr_a_addr, false, label_entry);
  void_4->setAlignment(4);
  StoreInst* void_5 = new StoreInst(int32_b, ptr_b_addr, false, label_entry);
  void_5->setAlignment(4);
  LoadInst* int32_6 = new LoadInst(ptr_a_addr, "", false, label_entry);
  int32_6->setAlignment(4);
  LoadInst* int32_7 = new LoadInst(ptr_b_addr, "", false, label_entry);
  int32_7->setAlignment(4);
  std::vector<Value*> int32_call_params;
  int32_call_params.push_back(int32_6);
  int32_call_params.push_back(int32_7);
  CallInst* int32_call = CallInst::Create(func__Z8deep_addii, int32_call_params, "call", label_entry);
  int32_call->setCallingConv(CallingConv::C);
  int32_call->setTailCall(false);
  AttributeSet int32_call_PAL;
  int32_call->setAttributes(int32_call_PAL);
  
  ReturnInst::Create(mod->getContext(), int32_call, label_entry);
  
 }
 
 // Function: sub (func_sub)
 {
  Function::arg_iterator args = func_sub->arg_begin();
  Value* int32_a_9 = args++;
  int32_a_9->setName("a");
  Value* int32_b_10 = args++;
  int32_b_10->setName("b");
  
  BasicBlock* label_entry_11 = BasicBlock::Create(mod->getContext(), "entry",func_sub,0);
  
  // Block entry (label_entry_11)
  AllocaInst* ptr_a_addr_12 = new AllocaInst(IntegerType::get(mod->getContext(), 32), "a.addr", label_entry_11);
  ptr_a_addr_12->setAlignment(4);
  AllocaInst* ptr_b_addr_13 = new AllocaInst(IntegerType::get(mod->getContext(), 32), "b.addr", label_entry_11);
  ptr_b_addr_13->setAlignment(4);
  StoreInst* void_14 = new StoreInst(int32_a_9, ptr_a_addr_12, false, label_entry_11);
  void_14->setAlignment(4);
  StoreInst* void_15 = new StoreInst(int32_b_10, ptr_b_addr_13, false, label_entry_11);
  void_15->setAlignment(4);
  LoadInst* int32_16 = new LoadInst(ptr_a_addr_12, "", false, label_entry_11);
  int32_16->setAlignment(4);
  LoadInst* int32_17 = new LoadInst(ptr_b_addr_13, "", false, label_entry_11);
  int32_17->setAlignment(4);
  std::vector<Value*> int32_call_18_params;
  int32_call_18_params.push_back(int32_16);
  int32_call_18_params.push_back(int32_17);
  CallInst* int32_call_18 = CallInst::Create(func__Z8deep_subii, int32_call_18_params, "call", label_entry_11);
  int32_call_18->setCallingConv(CallingConv::C);
  int32_call_18->setTailCall(false);
  AttributeSet int32_call_18_PAL;
  int32_call_18->setAttributes(int32_call_18_PAL);
  
  ReturnInst::Create(mod->getContext(), int32_call_18, label_entry_11);
  
 }
 
 return mod;
}
